In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Path("data/raw").mkdir(parents=True, exist_ok=True)

df_source = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "Diana", "Eva"],
    "age": [25, np.nan, 35, 29, 50],
    "salary": [50000, 60000, np.nan, 70000, 120000],
    "department": ["IT", "HR", "IT", np.nan, "IT"]
})

df_source.to_csv("../data/raw/employees_missing.csv", index=False)
df_source

      name   age    salary department
0    Alice  25.0   50000.0         IT
1      Bob   NaN   60000.0         HR
2  Charlie  35.0       NaN         IT
3    Diana  29.0   70000.0        NaN
4      Eva  50.0  120000.0         IT

In [4]:
df = pd.read_csv("../data/raw/employees_missing.csv")
df

      name   age    salary department
0    Alice  25.0   50000.0         IT
1      Bob   NaN   60000.0         HR
2  Charlie  35.0       NaN         IT
3    Diana  29.0   70000.0        NaN
4      Eva  50.0  120000.0         IT

In [63]:
df.head()
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   age         4 non-null      float64
 2   salary      4 non-null      float64
 3   department  4 non-null      str
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

In [64]:
df.isna()

    name    age  salary  department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False  False   False       False

In [65]:
df.isna().sum()
df

      name   age    salary department
0    Alice  25.0   50000.0         IT
1      Bob   NaN   60000.0         HR
2  Charlie  35.0       NaN         IT
3    Diana  29.0   70000.0        NaN
4      Eva  50.0  120000.0         IT

In [66]:
df["age"] = df["age"].fillna(df["age"].mean())
df

      name    age    salary department
0    Alice  25.00   50000.0         IT
1      Bob  34.75   60000.0         HR
2  Charlie  35.00       NaN         IT
3    Diana  29.00   70000.0        NaN
4      Eva  50.00  120000.0         IT

In [67]:
df["salary"] = df["salary"].fillna(df["salary"].median())
df

      name    age    salary department
0    Alice  25.00   50000.0         IT
1      Bob  34.75   60000.0         HR
2  Charlie  35.00   65000.0         IT
3    Diana  29.00   70000.0        NaN
4      Eva  50.00  120000.0         IT

In [68]:
df = df.dropna(subset="department")
df

      name    age    salary department
0    Alice  25.00   50000.0         IT
1      Bob  34.75   60000.0         HR
2  Charlie  35.00   65000.0         IT
4      Eva  50.00  120000.0         IT

In [69]:
df.isna().sum()

name          0
age           0
salary        0
department    0
dtype: int64

In [ ]:
# Task A
df.head(3)
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   age         4 non-null      float64
 2   salary      4 non-null      float64
 3   department  4 non-null      str
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

In [12]:
# Task B
df.isna().sum()

name          0
age           1
salary        1
department    1
dtype: int64

In [15]:
# Task C
df["age"] = df["age"].fillna(df["age"].mean())
df["salary"] = df["salary"].fillna(df["salary"].median())
df

      name    age    salary department
0    Alice  25.00   50000.0         IT
1      Bob  34.75   60000.0         HR
2  Charlie  35.00   65000.0         IT
3    Diana  29.00   70000.0        NaN
4      Eva  50.00  120000.0         IT

In [31]:
# Task D
df = df.dropna(subset=["department"])
df

      name    age    salary department
0    Alice  25.00   50000.0         IT
1      Bob  34.75   60000.0         HR
2  Charlie  35.00   65000.0         IT
4      Eva  50.00  120000.0         IT

In [30]:
# Task E
df.isna().sum()

name          0
age           0
salary        0
department    0
dtype: int64