In [2]:
import pandas as pd

In [ ]:
df_source = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "Diana", "Eva", "Frank"],
    "age": [25, 40, 35, 29, 50, 31],
    "salary": [50000, 90000, 80000, 60000, 120000, 75000],
    "department": ["IT", "HR", "IT", "Marketing", "IT", "HR"],
    "experience": [2, 15, 10, 5, 20, 7]
})

df_source.to_csv("../data/raw/employees_groupby.csv", index=False)
df_source

      name  age  salary department  experience
0    Alice   25   50000         IT           2
1      Bob   40   90000         HR          15
2  Charlie   35   80000         IT          10
3    Diana   29   60000  Marketing           5
4      Eva   50  120000         IT          20
5    Frank   31   75000         HR           7

In [4]:
df = pd.read_csv("../data/raw/employees_groupby.csv")
df

      name  age  salary department  experience
0    Alice   25   50000         IT           2
1      Bob   40   90000         HR          15
2  Charlie   35   80000         IT          10
3    Diana   29   60000  Marketing           5
4      Eva   50  120000         IT          20
5    Frank   31   75000         HR           7

In [5]:
df["department"].value_counts()

department
IT           3
HR           2
Marketing    1
Name: count, dtype: int64

In [9]:
df.groupby("department")["salary"].mean()

department
HR           82500.000000
IT           83333.333333
Marketing    60000.000000
Name: salary, dtype: float64

In [10]:
df.groupby("department")["salary"].agg(["mean", "median", "min", "max"])

                    mean   median    min     max
department
HR          82500.000000  82500.0  75000   90000
IT          83333.333333  80000.0  50000  120000
Marketing   60000.000000  60000.0  60000   60000

In [11]:
df.groupby("department")["experience"].mean()

department
HR           11.000000
IT           10.666667
Marketing     5.000000
Name: experience, dtype: float64

In [39]:
# Task A
df["department"].value_counts()

department
IT           3
HR           2
Marketing    1
Name: count, dtype: int64

In [15]:
# Task B
df.groupby("department")["salary"].mean()

department
HR           82500.000000
IT           83333.333333
Marketing    60000.000000
Name: salary, dtype: float64

In [ ]:
# Task C
df.groupby("department")["salary"].agg(["mean", "median", "min", "max"])

                    mean   median    min     max
department
HR          82500.000000  82500.0  75000   90000
IT          83333.333333  80000.0  50000  120000
Marketing   60000.000000  60000.0  60000   60000

In [17]:
# Task D
df.groupby("department")["experience"].mean()

department
HR           11.000000
IT           10.666667
Marketing     5.000000
Name: experience, dtype: float64

In [ ]:
# Task E
# df.groupby("department")["salary"].mean().sort_values(ascending=False).index[0]
df.groupby("department")["salary"].mean().idxmax()

'IT'