In [1]:
import pandas as pd

In [4]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "Diana"],
    "department_id": [10, 20, 10, 30]
})

departments = pd.DataFrame({
    "department_id": [10, 20],
    "department_name": ["IT", "HR"]
})

employees

   employee_id     name  department_id
0            1    Alice             10
1            2      Bob             20
2            3  Charlie             10
3            4    Diana             30

In [5]:
employees.merge(departments, on="department_id", how="inner")

   employee_id     name  department_id department_name
0            1    Alice             10              IT
1            2      Bob             20              HR
2            3  Charlie             10              IT

In [6]:
employees.merge(departments, on="department_id", how="left")

   employee_id     name  department_id department_name
0            1    Alice             10              IT
1            2      Bob             20              HR
2            3  Charlie             10              IT
3            4    Diana             30             NaN

In [37]:
employees.merge(departments, on="department_id", how="outer")

   employee_id     name  department_id department_name
0          1.0    Alice             10              IT
1          3.0  Charlie             10              IT
2          2.0      Bob             20              HR
3          4.0    Diana             30             NaN
4          NaN      NaN             40         Finance

In [ ]:
# Task dataset_01
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "Diana"],
    "department_id": [10, 20, 10, 30]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 40],
    "department_name": ["IT", "HR", "Finance"]
})
employees

   employee_id     name  department_id
0            1    Alice             10
1            2      Bob             20
2            3  Charlie             10
3            4    Diana             30

In [13]:
departments

   department_id department_name
0             10              IT
1             20              HR
2             40         Finance

In [41]:
# Task A
employees.merge(departments, on="department_id", how="left")

   employee_id     name  department_id department_name
0            1    Alice             10              IT
1            2      Bob             20              HR
2            3  Charlie             10              IT
3            4    Diana             30             NaN

In [42]:
# Task dataset_02
salaries = pd.DataFrame({
    "employee_id": [1, 2, 3],
    "salary": [50000, 70000, 90000]
})
salaries

   employee_id  salary
0            1   50000
1            2   70000
2            3   90000

In [58]:
# Task B
employees.merge(salaries, on="employee_id", how="left")

   employee_id     name  department_id   salary
0            1    Alice             10  50000.0
1            2      Bob             20  70000.0
2            3  Charlie             10  90000.0
3            4    Diana             30      NaN

In [59]:
# Task C
clear_dataset = (
    employees
    .merge(departments, on="department_id", how="left")
    .merge(salaries, on="employee_id", how="left")
)
clear_dataset

   employee_id     name  department_id department_name   salary
0            1    Alice             10              IT  50000.0
1            2      Bob             20              HR  70000.0
2            3  Charlie             10              IT  90000.0
3            4    Diana             30             NaN      NaN

In [62]:
# Task D
clear_dataset.isna().sum()

employee_id        0
name               0
department_id      0
department_name    1
salary             1
dtype: int64

NaN появились, потому что для некоторых ключей не нашлось совпадений
в связанных таблицах:
- у Diana department_id = 30, но такого id нет в departments
- у Diana employee_id = 4, но такого id нет в salaries
Поэтому после left merge соответствующие значения стали NaN.

Task E\
left merge оставляет все что есть в левой таблице и добавляет все из второй(правой), это удобно для наращивания датасета из нужных признаков/столбцов, а благодаря inner merge, можно составить таблицу пересечений на основе какого-либо признака, например id, названия департамента итд